### ISSUE TITLE
how to use ply2stl?

### ISSUE THREAD

**Issue by longzeyilang** [waqarsqureshi/ply2stl#1]
Hi, thank you for your job.  I have downloaded the vcglib in https://github.com/cnr-isti-vclab/vcglib.
An error about "fatal error: ply2stlConfig.h: no file" occurred, I do not know solve it?

**Comment by waqarsqureshi** [comment]
Please use CMAKE GUI to configure. The file will be generated from ply2stlConfig.h.in

configure_file (
  "${PROJECT_SOURCE_DIR}/ply2stlConfig.h.in"
  "${PROJECT_BINARY_DIR}/ply2stlConfig.h"
  )
